service:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmap?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    

mybatis:
  typeAliasesPackage: com.zb.studentmap.domain
  mapperLocations: classpath:mapper/*.xml  